name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  node_version: 16

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ env.node_version }}
      - run: yarn install --frozen-lockfile
      - run: yarn build

  vale:
    name: runner/vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          version: 2.29.4
          files: '[
            "docs/",
            "README.md",
            "style-checker-notes.md",
            "style-guide.md"
            ]'
          fail_on_error: true
          reporter: github-pr-check
          vale_flags: "--minAlertLevel=error"
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
